### ISSUE TITLE
next validator task

### ISSUE THREAD

**Issue by Oleg-docent** [ben-eb/css-values#11]
Hi, Ben! I want next validator task)

**Comment by ben-eb** [comment]
Hi Oleg! 😄

Do you want to take `will-change`? We need an `isAnimateableFeature` validator for this property. The syntax is quite simple - `scroll-position | contents | <custom-ident>` - check that it is either of those keywords or pass it through `isCustomIdent`.

More info on this property at https://developer.mozilla.org/en/docs/Web/CSS/will-change.

**Comment by ben-eb** [comment]
Implemented in https://github.com/ben-eb/css-values/pull/14. 😄
